name       : imath
version    : 3.1.3
release    : 2
source     :
    - https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.1.3.tar.gz : 0bf7ec51162c4d17a4c5b850fb3f6f7a195cff9fa71f4da7735f74d7b5124320
license    : BSD-3-Clause
component  : multimedia.library
summary    : Imath is a library of 2D and 3D vector, matrix, and math operations for computer graphics
description: |
    Imath is a basic, light-weight, and efficient C++ representation of 2D and 3D vectors and matrices and other simple but useful mathematical objects, functions, and data types common in computer graphics applications, including the "half" 16-bit floating-point type.
replaces   :
    - ilmbase
    - devel :
        - ilmbase-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
